name: Train

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 0,6,12,18 * * *'

jobs:
  build-on-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: pre
      run: pip install keras tensorflow

    - name: get-model
      run: git clone https://github.com/SUSTechHSAS/aichesser-model.git
        
    - name: run
      run: python3 ./AlphaZero_train.py 5 450 4 ./aichesser-model/res.keras res.keras

    - name: commit
      env:
        TOKEN: ${{ secrets.MODEL_CONTENT_TOKEN }}
      run: |
        mv ./aichesser-model/res.keras ./last.keras
        mv ./res.keras ./aichesser-model
        echo update >> ./temp.txt
        cd aichesser-model
        git config --global user.email "41898282+github-actions[bot]@sustechhsas.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git -c credential.helper= -c core.quotepath=false -c log.showSignature=false add --ignore-errors -A -f -- res.keras
        git -c credential.helper= -c core.quotepath=false -c log.showSignature=false commit -F ../temp.txt --

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        repository: SUSTechHSAS/aichesser-model
        directory: ./aichesser-model
        github_token: ${{ secrets.MODEL_CONTENT_TOKEN }}
        force: true


    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: iter
        path: ./*
